services:
  bot:
    build: .
    container_name: parser_bot
    volumes:
      - .:/app
      - dblite_data:/app/database/db
      - sessions_data:/app/sessions
    env_file:
      - .env
    command: python main.py

volumes:
  dblite_data:
    name: dblite_data
  sessions_data:
    name: sessions_data
    driver: local
